// Seed data — these will eventually come from Supabase
// For now this lets us ship the UI immediately

import { Recipe, Collection } from './supabase';

export const sampleRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Bolognese',
    subtitle: 'A slow-built, deeply savory meat sauce from Bologna',
    source_url: 'https://www.seriouseats.com/the-best-slow-cooked-bolognese-sauce-recipe',
    source_name: 'Serious Eats',
    time_minutes: 120,
    difficulty: 'Medium',
    servings: 4,
    cuisine: 'Italian',
    tags: ['Pasta', 'Comfort food', 'Weeknight'],
    is_featured: true,
    featured_tag: 'Comfort food',
    ingredients: [
      { name: 'Beef mince', amount: '500g' },
      { name: 'Onion', amount: '1 large' },
      { name: 'Carrot', amount: '2 medium' },
      { name: 'Celery', amount: '2 stalks' },
      { name: 'Tomato passata', amount: '2 cans' },
      { name: 'Red wine', amount: '1 glass' },
      { name: 'Whole milk', amount: '120ml' },
      { name: 'Olive oil', amount: '2 tbsp' },
      { name: 'Fresh basil', amount: 'handful' },
      { name: 'Parmesan', amount: 'to serve' },
    ],
    steps: [
      { number: 1, title: 'Dice onion, carrot, celery', detail: 'Fine, even mince. 3-4mm pieces.', sensory_cues: 'Uniform small cubes. Smells sharp and fresh.', milestone: 'Even, tiny dice across the board' },
      { number: 2, title: 'Sauté soffritto in olive oil', detail: 'Medium heat, 8-10 min until translucent and sweet.', sensory_cues: 'Sweet, jammy aroma. Softened and glassy, not browned.', milestone: 'Soffritto is translucent and sweet' },
      { number: 3, title: 'Brown the mince', detail: "High heat. Break into small pieces. Don't stir too often.", sensory_cues: 'Deep sizzle. Caramelized edges. Rich meaty smell.', milestone: 'Mince is browned with crisp edges' },
      { number: 4, title: 'Deglaze with wine', detail: 'Full glass of red. Scrape the fond. Cook until nearly dry.', sensory_cues: 'Sharp wine steam. Fond dissolves into deep color.', milestone: 'Wine has cooked off almost completely' },
      { number: 5, title: 'Add tomato passata', detail: 'Two cans. Stir through, bring to gentle simmer.', sensory_cues: 'Bright tomato aroma. Orange-red color. Gentle bubbling.', milestone: 'Sauce is simmering gently' },
      { number: 6, title: 'Reduce the sauce', detail: 'Low heat, 45 min. Stir every 10 min. Sauce coats the back of a spoon.', sensory_cues: 'Deep brick red. Nutty smell. No visible pooling liquid.', milestone: 'Sauce coats the back of a spoon' },
      { number: 7, title: 'Add milk', detail: 'Half cup whole milk. Stir gently until absorbed.', sensory_cues: 'Lightens slightly. Creamier texture. Mellower aroma.', milestone: 'Milk is fully absorbed into sauce' },
      { number: 8, title: 'Season and rest', detail: 'Salt, pepper, fresh basil. Rest 10 min off heat.', sensory_cues: 'Fresh herbal aroma. Balanced, round flavor.', milestone: 'Seasoned and resting off heat' },
      { number: 9, title: 'Cook pasta and serve', detail: 'Al dente. Toss with sauce. Finish with parmesan.', sensory_cues: 'Pasta coated in sauce. Glossy. Steam rising.', milestone: 'Pasta is plated and sauced' },
    ],
    created_at: '2026-04-20T00:00:00Z',
    updated_at: '2026-04-29T00:00:00Z',
  },
  {
    id: '2',
    title: 'Chicken Tikka Masala',
    subtitle: 'Charred yogurt-marinated chicken in a creamy spiced tomato sauce',
    source_url: 'https://www.seriouseats.com/chicken-tikka-masala-recipe',
    source_name: 'Serious Eats',
    time_minutes: 45,
    difficulty: 'Medium',
    servings: 4,
    cuisine: 'Indian',
    tags: ['Curry', 'Comfort food', 'Weeknight'],
    is_featured: true,
    featured_tag: 'Quick dinner',
    ingredients: [
      { name: 'Chicken thighs', amount: '800g' },
      { name: 'Greek yogurt', amount: '200g' },
      { name: 'Garam masala', amount: '2 tbsp' },
      { name: 'Turmeric', amount: '1 tsp' },
      { name: 'Cumin', amount: '1 tsp' },
      { name: 'Tomato puree', amount: '400g tin' },
      { name: 'Double cream', amount: '200ml' },
      { name: 'Onion', amount: '2 large' },
      { name: 'Garlic', amount: '4 cloves' },
      { name: 'Ginger', amount: '2 inch piece' },
      { name: 'Butter', amount: '30g' },
      { name: 'Fresh coriander', amount: 'handful' },
    ],
    steps: [
      { number: 1, title: 'Marinate chicken', detail: 'Yogurt, garam masala, turmeric, cumin. Refrigerate 1 hour or overnight.', milestone: 'Chicken is coated and marinating' },
      { number: 2, title: 'Grill the chicken', detail: 'Broil until charred. Cut into bite-sized pieces.', milestone: 'Chicken has charred edges' },
      { number: 3, title: 'Sauté onions', detail: 'Butter until golden. Add garlic and ginger, cook 2 minutes.', milestone: 'Onions are golden and fragrant' },
      { number: 4, title: 'Build the sauce', detail: 'Add tomato puree and remaining spices. Simmer 15 minutes.', milestone: 'Sauce is thickened and aromatic' },
      { number: 5, title: 'Add cream and chicken', detail: 'Stir in cream, add chicken. Simmer 10 minutes.', milestone: 'Sauce coats the chicken' },
      { number: 6, title: 'Finish and serve', detail: 'Butter and fresh coriander. Serve with basmati or naan.', milestone: 'Plated with fresh herbs' },
    ],
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-05-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Cacio e Pepe',
    subtitle: 'Three ingredients, infinite technique',
    source_name: 'Bon Appétit',
    time_minutes: 20,
    difficulty: 'Easy',
    servings: 2,
    cuisine: 'Italian',
    tags: ['Pasta', 'Quick', 'Weeknight'],
    is_featured: true,
    featured_tag: 'Quick dinner',
    ingredients: [
      { name: 'Spaghetti', amount: '200g' },
      { name: 'Pecorino Romano', amount: '100g, finely grated' },
      { name: 'Black pepper', amount: '2 tbsp, freshly cracked' },
    ],
    steps: [
      { number: 1, title: 'Toast pepper', detail: 'Dry pan, medium heat, 2 minutes until fragrant.', milestone: 'Pepper is toasted and aromatic' },
      { number: 2, title: 'Cook pasta', detail: 'Very salty water. Pull 2 min early — it finishes in the pan.', milestone: 'Pasta is very al dente' },
      { number: 3, title: 'Make the emulsion', detail: 'Pasta water + pecorino, whisk off heat into a creamy paste.', milestone: 'Smooth, creamy cheese sauce' },
      { number: 4, title: 'Toss and serve', detail: 'Add pasta to sauce, toss with tongs. Add water if needed.', milestone: 'Glossy, coated strands' },
    ],
    created_at: '2026-05-02T00:00:00Z',
    updated_at: '2026-05-02T00:00:00Z',
  },
  {
    id: '4',
    title: 'Miso Butter Salmon',
    subtitle: 'Caramelized, umami-rich, on the table in 25 minutes',
    source_name: '@halfbakedharvest',
    source_url: 'https://www.halfbakedharvest.com/miso-butter-salmon',
    time_minutes: 25,
    difficulty: 'Easy',
    servings: 2,
    cuisine: 'Japanese-inspired',
    tags: ['Seafood', 'Quick', 'Weeknight', 'Healthy'],
    is_featured: true,
    featured_tag: 'Comfort food',
    ingredients: [
      { name: 'Salmon fillets', amount: '2 pieces' },
      { name: 'White miso paste', amount: '2 tbsp' },
      { name: 'Butter', amount: '30g' },
      { name: 'Honey', amount: '1 tbsp' },
      { name: 'Soy sauce', amount: '1 tbsp' },
      { name: 'Rice', amount: 'to serve' },
      { name: 'Sesame seeds', amount: 'to garnish' },
    ],
    steps: [
      { number: 1, title: 'Mix the glaze', detail: 'Miso, melted butter, honey, soy. Whisk until smooth.', milestone: 'Smooth, glossy glaze' },
      { number: 2, title: 'Coat salmon', detail: 'Brush generously on all sides. Let sit 5 minutes.', milestone: 'Salmon is well coated' },
      { number: 3, title: 'Broil', detail: 'High heat, 8-10 minutes until caramelized and flaky.', milestone: 'Golden, bubbly glaze on top' },
      { number: 4, title: 'Serve', detail: 'Over rice with sesame seeds and any extra glaze drizzled.', milestone: 'Plated over fluffy rice' },
    ],
    created_at: '2026-05-03T00:00:00Z',
    updated_at: '2026-05-03T00:00:00Z',
  },
  {
    id: '5',
    title: 'Pad Thai',
    subtitle: 'Sweet, sour, salty, spicy — all in one wok',
    source_name: 'Woks of Life',
    time_minutes: 30,
    difficulty: 'Easy',
    servings: 2,
    cuisine: 'Thai',
    tags: ['Noodles', 'Quick', 'Weeknight'],
    is_featured: false,
    ingredients: [
      { name: 'Rice noodles', amount: '200g' },
      { name: 'Shrimp or chicken', amount: '200g' },
      { name: 'Eggs', amount: '2' },
      { name: 'Bean sprouts', amount: '1 cup' },
      { name: 'Tamarind paste', amount: '2 tbsp' },
      { name: 'Fish sauce', amount: '2 tbsp' },
      { name: 'Palm sugar', amount: '1 tbsp' },
      { name: 'Peanuts', amount: 'crushed, to serve' },
      { name: 'Lime', amount: '1, quartered' },
    ],
    steps: [
      { number: 1, title: 'Soak noodles', detail: 'Room temp water, 30 minutes until pliable but firm.', milestone: 'Noodles bend without snapping' },
      { number: 2, title: 'Make the sauce', detail: 'Tamarind, fish sauce, sugar. Stir until sugar dissolves.', milestone: 'Balanced sweet-sour-salty sauce' },
      { number: 3, title: 'Stir fry protein', detail: 'High heat wok, cook shrimp/chicken. Push to side, scramble eggs.', milestone: 'Protein cooked, eggs set' },
      { number: 4, title: 'Add noodles and sauce', detail: 'Toss everything together. Add sprouts last for crunch.', milestone: 'Noodles coated, slightly charred' },
    ],
    created_at: '2026-04-25T00:00:00Z',
    updated_at: '2026-04-25T00:00:00Z',
  },
  {
    id: '6',
    title: 'Lamb Ragu',
    subtitle: 'Falling-apart lamb in a rich wine sauce — worth the wait',
    source_name: 'Ottolenghi Simple',
    time_minutes: 90,
    difficulty: 'Medium',
    servings: 4,
    cuisine: 'Italian',
    tags: ['Pasta', 'Date night', 'Weekend project'],
    is_featured: true,
    featured_tag: 'Date night',
    ingredients: [
      { name: 'Lamb shoulder', amount: '600g, diced' },
      { name: 'Red wine', amount: '250ml' },
      { name: 'Tinned tomatoes', amount: '400g' },
      { name: 'Rosemary', amount: '2 sprigs' },
      { name: 'Garlic', amount: '4 cloves' },
      { name: 'Pappardelle', amount: '300g' },
      { name: 'Parmesan', amount: 'to serve' },
    ],
    steps: [
      { number: 1, title: 'Brown the lamb', detail: 'Season and sear in batches until deeply colored.', milestone: 'Dark crust on all sides' },
      { number: 2, title: 'Build aromatics', detail: 'Garlic, rosemary, deglaze with wine.', milestone: 'Wine reduced by half' },
      { number: 3, title: 'Braise', detail: 'Add tomatoes, cover, low heat 1 hour.', milestone: 'Lamb falls apart with a fork' },
      { number: 4, title: 'Shred and serve', detail: 'Break up lamb, toss with pappardelle.', milestone: 'Rich sauce coating wide noodles' },
    ],
    created_at: '2026-04-28T00:00:00Z',
    updated_at: '2026-04-28T00:00:00Z',
  },
  {
    id: '7',
    title: 'Thai Basil Chicken',
    subtitle: 'Spicy, aromatic, fifteen minutes flat',
    source_name: 'TikTok @maboroshi',
    time_minutes: 15,
    difficulty: 'Easy',
    servings: 2,
    cuisine: 'Thai',
    tags: ['Quick', 'Spicy', 'Weeknight'],
    is_featured: true,
    featured_tag: 'Something new',
    ingredients: [
      { name: 'Chicken mince', amount: '400g' },
      { name: 'Thai basil', amount: 'large handful' },
      { name: 'Thai chilies', amount: '3-5, sliced' },
      { name: 'Garlic', amount: '5 cloves, minced' },
      { name: 'Soy sauce', amount: '2 tbsp' },
      { name: 'Oyster sauce', amount: '1 tbsp' },
      { name: 'Fish sauce', amount: '1 tbsp' },
      { name: 'Sugar', amount: '1 tsp' },
      { name: 'Jasmine rice', amount: 'to serve' },
      { name: 'Fried egg', amount: '1 per serving' },
    ],
    steps: [
      { number: 1, title: 'Fry garlic and chilies', detail: 'Hot wok, oil, 30 seconds until fragrant.', milestone: 'Sizzling and aromatic' },
      { number: 2, title: 'Cook chicken', detail: 'Add mince, break up, cook 3-4 minutes.', milestone: 'No pink remaining' },
      { number: 3, title: 'Add sauces', detail: 'Soy, oyster, fish sauce, sugar. Toss.', milestone: 'Glossy and coated' },
      { number: 4, title: 'Finish with basil', detail: 'Kill heat, fold in basil until wilted. Serve over rice with fried egg.', milestone: 'Basil just wilted, still bright' },
    ],
    created_at: '2026-05-03T00:00:00Z',
    updated_at: '2026-05-03T00:00:00Z',
  },
  {
    id: '8',
    title: 'Dal Makhani',
    subtitle: 'Buttery black lentils, slow-cooked to velvet',
    source_name: 'Madhur Jaffrey',
    time_minutes: 90,
    difficulty: 'Easy',
    servings: 4,
    cuisine: 'Indian',
    tags: ['Lentils', 'Comfort food', 'Vegetarian'],
    is_featured: false,
    ingredients: [
      { name: 'Black urad dal', amount: '250g' },
      { name: 'Kidney beans', amount: '100g' },
      { name: 'Butter', amount: '60g' },
      { name: 'Cream', amount: '100ml' },
      { name: 'Tomato puree', amount: '200g' },
      { name: 'Ginger-garlic paste', amount: '2 tbsp' },
      { name: 'Garam masala', amount: '1 tsp' },
      { name: 'Kashmiri chili', amount: '1 tsp' },
    ],
    steps: [
      { number: 1, title: 'Soak and cook lentils', detail: 'Overnight soak, pressure cook or simmer 45 min.', milestone: 'Lentils are soft but hold shape' },
      { number: 2, title: 'Make the tadka', detail: 'Butter, ginger-garlic, spices, tomato. Cook 10 min.', milestone: 'Oil separates from masala' },
      { number: 3, title: 'Combine and simmer', detail: 'Add lentils to tadka. Low heat 30 min, stirring.', milestone: 'Thick, creamy consistency' },
      { number: 4, title: 'Finish with cream', detail: 'Stir in cream and butter. Serve with naan.', milestone: 'Rich, velvety, glossy' },
    ],
    created_at: '2026-04-22T00:00:00Z',
    updated_at: '2026-04-22T00:00:00Z',
  },
];

export const sampleCollections: Collection[] = [
  { id: '1', name: 'Weeknight Dinners', icon: 'clock', color: 'terra', recipe_count: 5, created_at: '2026-04-20T00:00:00Z' },
  { id: '2', name: 'Date Night', icon: 'heart', color: 'sage', recipe_count: 3, created_at: '2026-04-20T00:00:00Z' },
  { id: '3', name: 'Meal Prep', icon: 'box', color: 'gold', recipe_count: 2, created_at: '2026-04-20T00:00:00Z' },
];

export const seasonalSpotlight = {
  ingredient: 'Spring Asparagus',
  description: 'Tender, grassy, and at its peak right now. Roast it, shave it raw, or make it the star.',
  recipes: [
    { name: 'Asparagus Risotto', time: '45 min' },
    { name: 'Shaved Salad', time: '10 min' },
    { name: 'Roasted + Egg', time: '20 min' },
  ],
};

export const tipOfTheDay = "Salt your pasta water until it tastes like the sea. Under-salted water means under-seasoned pasta, no matter how good your sauce is.";
